services:
  - type: web
    name: autobot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: BOT_TOKEN
        value: your_bot_token
      - key: CHANNEL_ID
        value: -1001234567890  # তোমার চ্যানেল আইডি
      - key: BOT_OWNER
        value: 123456789  # তোমার টেলিগ্রাম ইউজার আইডি
      - key: DATABASE_URL
        value: your_mongodb_url
      - key: RESULTS_COUNT
        value: 5
